### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Abdizriel** [m1ome/phalcon-datatables#13]
Hello,

How can I mmake server-side pagination with your plugin?
I thought that by default it will select by defafult only 20 rows, but in payload I can see that it fetch all data:

recordsFiltered: 1847
recordsTotal: 1847

**Comment by m1ome** [comment]
By default it uses pagination for QueryBuilder, and filter for ResultSet.
It seek through post parameter called "length":

```php
  public function getLimit() {
    return $this->params['length'];
  }
```

You can look at params parsing in `/src/ParamsParser.php`.
Maybe you can provide your Ajax request?

**Comment by Abdizriel** [comment]
I'm using Array Adapter since I've to process data before sending them to DataTables

**Comment by m1ome** [comment]
Please, provide your XHR request.

**Comment by m1ome** [comment]
No new information, closed, due to lack of information
