### ISSUE TITLE
search not working when using alias and multiple models

### ISSUE THREAD

**Issue by stefanchiriac** [m1ome/phalcon-datatables#17]
Hello,

When using builder and relationships between 2 models, column search and global search no longer works and returns all results.

The problem seems to be from QueryBuilder::getResponse on $this->bind()

```
      $builder = $this->modelsManager->createBuilder()
        ->columns('u.id, u.username, u.email, r.name, u.status')
        ->addFrom('Core\Models\User', 'u')
        ->addFrom('Core\Models\Role', 'r')
        ->where('u.role_id = r.id');
```

Thanks

**Comment by kaanc** [comment]
yes because query builder where working only first draw. after its not work. I open also this issues.

**Comment by stefanchiriac** [comment]
this is fixed in my pull request, but seems like no one is maintaining this repo anymore. Is available on my fork https://github.com/magnxpyr/phalcon-datatables

**Comment by nathanhollows** [comment]
This is fantastic! Thank you
