### ISSUE TITLE
[BUG] orderby not working

### ISSUE THREAD

**Issue by advokata** [m1ome/phalcon-datatables#2]
Hello i have issue when i need to order by some column.

I see in profiler of the queries that there is no order by clause.

This is happen in fromBuilder.

I see that in arrayBuilder there is no filter. I try both and i preffer to use array but there is no way to search in columns or to order by something.

**Comment by advokata** [comment]
I fix this by changing AdapterInterface.php 

Line 100

From:   $column = $this->parser->getColumnById($columnId);

To: $column = $this->parser->getColumnById($orderBy['column']);

**Comment by m1ome** [comment]
If you look at tests every element (array, builder and PHQL) have a order support. Can you provide how your Ajax call is look like?

**Comment by advokata** [comment]
This is the Post data:

draw:4
columns[0][data]:0
columns[0][name]:
columns[0][searchable]:true
columns[0][orderable]:true
columns[0][search][value]:
columns[0][search][regex]:false
columns[1][data]:rID
columns[1][name]:
columns[1][searchable]:true
columns[1][orderable]:true
columns[1][search][value]:
columns[1][search][regex]:false
columns[2][data]:brand
columns[2][name]:
columns[2][searchable]:true
columns[2][orderable]:true
columns[2][search][value]:
columns[2][search][regex]:false
columns[3][data]:model
columns[3][name]:
columns[3][searchable]:true
columns[3][orderable]:true
columns[3][search][value]:
columns[3][search][regex]:false
columns[4][data]:regNo
columns[4][name]:
columns[4][searchable]:true
columns[4][orderable]:true
columns[4][search][value]:
columns[4][search][regex]:false
columns[5][data]:rname
columns[5][name]:
columns[5][searchable]:true
columns[5][orderable]:true
columns[5][search][value]:
columns[5][search][regex]:false
columns[6][data]:rliter
columns[6][name]:
columns[6][searchable]:true
columns[6][orderable]:true
columns[6][search][value]:
columns[6][search][regex]:false
columns[7][data]:rcost
columns[7][name]:
columns[7][searchable]:true
columns[7][orderable]:true
columns[7][search][value]:
columns[7][search][regex]:false
columns[8][data]:dateAdd
columns[8][name]:
columns[8][searchable]:true
columns[8][orderable]:true
columns[8][search][value]:
columns[8][search][regex]:false
columns[9][data]:rplace
columns[9][name]:
columns[9][searchable]:true
columns[9][orderable]:true
columns[9][search][value]:
columns[9][search][regex]:false
columns[10][data]:crTime
columns[10][name]:
columns[10][searchable]:true
columns[10][orderable]:true
columns[10][search][value]:
columns[10][search][regex]:false
order[0][column]:5
order[0][dir]:asc
start:0
length:100
search[value]:
search[regex]:false
firmID:2

**Comment by m1ome** [comment]
Fixed! Good catch :+1:
