### ISSUE TITLE
Empty Resultset.

### ISSUE THREAD

**Issue by advokata** [m1ome/phalcon-datatables#8]
<b>Fatal error</b>:  Call to a member function toArray() on boolean in <b>/var/www/html/app/vendor/m1ome/phalcon-datatables/src/DataTable.php</b> on line <b>62</b><br />

When there is no record according to ResultSet it return false. For example in case of empty table or not matched records. Could you add some check and if is false then return empty result which not make datatables shown Json Error Respond Alert.

**Comment by m1ome** [comment]
Fixed in 1.1.5 :+1:
